

package com.skydoves.compose.stability.compiler.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.skydoves.compose.stability.compiler.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/fir")
@TestDataPath("$PROJECT_ROOT")
public class FirDumpTestGenerated extends AbstractFirDumpTest {
  @Test
  public void testAllFilesPresentInFir() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/fir"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("MutableDataClass.kt")
  public void testMutableDataClass() {
    runTest("compiler-tests/src/test/data/dump/fir/MutableDataClass.kt");
  }

  @Test
  @TestMetadata("SimpleDataClass.kt")
  public void testSimpleDataClass() {
    runTest("compiler-tests/src/test/data/dump/fir/SimpleDataClass.kt");
  }

  @Test
  @TestMetadata("TraceRecompositionAnnotation.kt")
  public void testTraceRecompositionAnnotation() {
    runTest("compiler-tests/src/test/data/dump/fir/TraceRecompositionAnnotation.kt");
  }
}
