

package com.skydoves.compose.stability.compiler.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.skydoves.compose.stability.compiler.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("ComposableWithTraceRecomposition.kt")
  public void testComposableWithTraceRecomposition() {
    runTest("compiler-tests/src/test/data/dump/ir/ComposableWithTraceRecomposition.kt");
  }

  @Test
  @TestMetadata("MutableDataClass.kt")
  public void testMutableDataClass() {
    runTest("compiler-tests/src/test/data/dump/ir/MutableDataClass.kt");
  }

  @Test
  @TestMetadata("SimpleDataClass.kt")
  public void testSimpleDataClass() {
    runTest("compiler-tests/src/test/data/dump/ir/SimpleDataClass.kt");
  }

  @Test
  @TestMetadata("TraceRecompositionInjection.kt")
  public void testTraceRecompositionInjection() {
    runTest("compiler-tests/src/test/data/dump/ir/TraceRecompositionInjection.kt");
  }
}
